# Settings
baseurl = "http://byt-vodova.kremser.dev"
languageCode = "en-us"
title = "Byt Vodova 53"
theme = "autophugo"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[Author]
    name = "Jiri Kremser"
    email = "jiri.kremser@gmail.com"

[params]
    # Meta
    description = "Pronajem bytu na ulici Vodova"
    keywords = "byt, pronajem, inzerat"
    #msvalidate = ""
    #googlesiteverification = ""
    thumb_width = 800
    thumb_quality = 90
    #full_width = 960
    full_quality = 97
    #column_count = 2
    
    # Headerbar links
    # Do not put here too many links,
    # it will break mobile appearance

    [[params.header.links]]
    name = "Informace"
    url = "#footer"
    icon = "fa-info-circle"    
    
    # Footer panel


    [params.footer.paragraph]
    headline = "Informace o bytu"
    text = "Vlastník nabízí k pronájmu kompletně zrekonstruovaný, cihlový byt 2+KK s lodžií v Brně-Králově Poli, na ulici Vodova 53. Okna a lodžie jsou obracený na lipovou alej, která je nejdelší svého druhu v Brně. Koruny stromů stíní slunci a ochlazují okolí.<br/><br/>Velmi světlý, slunný byt s východní orientací nabízí kvalitní bydlení ve výborné poloze, se skvělou dostupností MHD (zastávka tramvaje, trolejbusu a autobusu Skácelova 200m), obchodu (potraviny Brněnka 200m) a koupaliště po rekonstrukcí Dobrák (400m). Ve dvoře (z druhé strany) je dětské hřiště. V okolí je veškerá občanská vybavenost - potraviny, zastávky, poliklinika, restaurace BUTCHER’s, Na Purkynce, Liquid Bread a jiné. Do technologického parku je to kousek pěšky nebo tři zastávky šalinou. Do centra 10 minut šalinou.<br/><br/>Bytová jednotka o celkové výměře 55,7 m2 (včetně lodžie 3,5 m2 a prostorného sklepa o výměře 7 m2) se nachází v 3 NP pětipatrového bytového domu po celkové revitalizaci. Byt po celkové rekonstrukci v roce 2014 - nová koupelna včetně rozvodů vody a odpadů (s vyhřívanou podlahou), kuchyňská linka ORESI s vestavěnými spotřebiči ZANUSSI, nové elektrické rozvody, plovoucí podlahy, bezpečnostní vstupní dveře do bytu. Vlastní plynový kotel BAXI v bytě (vytápění a ohřev vody). V celém domě nové stupačky, kvalitní plastová okna, zateplená fasáda. <br/><br/>Dispozice bytu: čistá podlahová plocha 45,2 m2 (předsíň 4,62 m2, koupelna +WC 4,26 m2, obývací pokoj +KK 16,88 m2, spížka s oknem 1,02 m2, ložnice 18,42 m2, lodžie 3,5 m2). Bezproblémové parkování. V ceně nájemného je zahrnuto používání veškerého vybavení bytu.<br/><br/><b>Cena: 14 600 Kč + zálohy na elektřinu a plyn (1300 Kč + 1100 Kč)</b><br/><br/>Tel. 776 867 151. Prosim realitní kanceláře nekontaktovat!"
    
    [params.footer.social]
    headline = "O mne"

    [[params.footer.social.links]]
    label = "Twitter"
    url = "https://twitter.com/JirkaKremser"
    icon = "fa-twitter"

    [[params.footer.social.links]]
    label = "Github"
    url = "https://github.com/jkremser"
    icon = "fa-github"

    [[params.footer.social.links]]
    label = "email"
    url = "mailto:jiri.kremser@gmail.com"
    icon = "fa-envelope"
    
    # Contact form
    
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'realEmail' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    
    [params.footer.contact]
    hide = false # Set this to true if you don't want to have a contact form on your site
    realEmail = "xyybbrlz"
    headline = "Napište mi"
    buttonText = "Poslat"
    resetText = "Reset"
    
    # 'warning' defines error messages for invalid inputs
    [params.footer.contact.name]
    text = "Jmeno *"
    warning = "Vlozte prosim sve jmeno"

    [params.footer.contact.email]
    text = "Váš email *"
    warning = "Vlozte prosim svuj email."

    [params.footer.contact.message]
    text = "Zpráva *"
    warning = "Vlozte zpravu"
    
    # Copyright
    [params.footer.copyright]
    name = "Jiří Kremser"

